# Generated by Django 3.0.2 on 2020-04-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-rating'], 'verbose_name_plural': 'Reviews'},
        ),
    ]
